#ifndef SERIAL_COMM_h
#define SERIAL_COMM_h

// #include "Arduino.h"
#define SERIAL_COMM_BUTTON_1 10
#define SERIAL_COMM_BUTTON_2 12
#define SERIAL_COMM_BUTTON_3 14
#define SERIAL_COMM_BUTTON_4 16
#define SERIAL_COMM_BUTTON_5 18
#define SERIAL_COMM_BUTTON_6 20
#define SERIAL_COMM_BUTTON_7 22
#define SERIAL_COMM_BUTTON_8 24
#define SERIAL_COMM_BUTTON_9 26
#define SERIAL_COMM_BUTTON_0 28

#define SERIAL_COMM_POWER_OFF 30
#define SERIAL_COMM_POWER_ON  40

#define SERIAL_COMM_PHASER_ON 50
#define SERIAL_COMM_PHASER_OFF 60
#define SERIAL_COMM_TORPEDO 70

#define SERIAL_COMM_NAV_BEACON_ON 90
#define SERIAL_COMM_NAV_BEACON_OFF 92
#define SERIAL_COMM_NAV_FLASHER_ON 94
#define SERIAL_COMM_NAV_FLASHER_OFF 96

#define SERIAL_COMM_CRYSTAL_COLOR 100
#define SERIAL_COMM_NACELLE_COLOR 110
#define SERIAL_COMM_SAUCER_SECTION 120

#define SERIAL_COMM_IMPULSE_DRIVE 130
#define SERIAL_COMM_WARP_DRIVE 150

#endif
