#ifndef SERIAL_COMM_h
#define EN1701-REFIT_h

// #include "Arduino.h"
#define SERIAL_COMM_POWER_OFF 10
#define SERIAL_COMM_POWER_ON  20

#define SERIAL_COMM_PHASER_ON 30
#define SERIAL_COMM_PHASER_OFF 40
#define SERIAL_COMM_TORPEDO 50

#define SERIAL_COMM_IMPULSE_0   60
#define SERIAL_COMM_IMPULSE_25  65
#define SERIAL_COMM_IMPULSE_50  70
#define SERIAL_COMM_IMPULSE_75  75
#define SERIAL_COMM_IMPULSE_100 80

#define SERIAL_COMM_NAV_BEACON_ON 90
#define SERIAL_COMM_NAV_BEACON_OFF 92
#define SERIAL_COMM_NAV_FLASHER_ON 94
#define SERIAL_COMM_NAV_FLASHER_OFF 96

#define SERIAL_COMM_CRYSTAL_COLOR 100

#define SERIAL_COMM_IMPULSE_DRIVE 130   //last digit represents level
#define SERIAL_COMM_WARP_DRIVE 150      //Last digit represents level

#endif
