#ifndef SERIAL_COMM_MK2_h
#define SERIAL_COMM_MK2_h

// #include "Arduino.h"
#define SERIAL_COMM_SAUCER_SECTION_1 1
#define SERIAL_COMM_SAUCER_SECTION_2 2
#define SERIAL_COMM_SAUCER_SECTION_3 3
#define SERIAL_COMM_SAUCER_SECTION_4 4
#define SERIAL_COMM_SAUCER_SECTION_5 5
#define SERIAL_COMM_SAUCER_SECTION_6 6
#define SERIAL_COMM_SAUCER_SECTION_BRIDGE 8
#define SERIAL_COMM_SAUCER_SECTION_LOUNGE 7

#define SERIAL_COMM_FLOOD_1 10
#define SERIAL_COMM_FLOOD_2 12
#define SERIAL_COMM_HANGER_SECTION 14
#define SERIAL_COMM_AFT_SECTION 16
#define SERIAL_COMM_BELLY_SECTION 18
#define SERIAL_COMM_ENGINEERING_SECTION_1 20
#define SERIAL_COMM_ENGINEERING_SECTION_2 22
#define SERIAL_COMM_NECK_SECTION 24
#define SERIAL_COMM_ARBORITUM 26

#define SERIAL_COMM_POWER_OFF 30
#define SERIAL_COMM_POWER_ON  40

#define SERIAL_COMM_PHASER_ON 50
#define SERIAL_COMM_PHASER_OFF 60
#define SERIAL_COMM_TORPEDO 70

#define SERIAL_COMM_NAV_BEACON_ON 90
#define SERIAL_COMM_NAV_BEACON_OFF 92
#define SERIAL_COMM_NAV_FLASHER_ON 94
#define SERIAL_COMM_NAV_FLASHER_OFF 96

#define SERIAL_COMM_RED_ALERT_ON 97
#define SERIAL_COMM_RED_ALERT_OFF 98

#define SERIAL_COMM_CRYSTAL_COLOR 100
#define SERIAL_COMM_NACELLE_COLOR 110
#define SERIAL_COMM_DEFLECTOR_COLOR 115
#define SERIAL_COMM_SAUCER_SECTION 120

#define SERIAL_COMM_IMPULSE_DRIVE 130
#define SERIAL_COMM_INCREASE_IMPULSE_DRIVE 135
#define SERIAL_COMM_DECREASE_IMPULSE_DRIVE 140
#define SERIAL_COMM_START_WARP_DRIVE 150
#define SERIAL_COMM_STOP_WARP_DRIVE 152
#define SERIAL_COMM_INCREASE_WARP_DRIVE 155
#define SERIAL_COMM_DECREASE_WARP_DRIVE 160

#endif
